-- we don't know how to generate root <with-no-name> (class Root) :(

comment on database postgres is 'default administrative connection database';

create sequence adminaccount_seq
    increment by 50;

alter sequence adminaccount_seq owner to postgres;

create sequence answer_seq
    increment by 50;

alter sequence answer_seq owner to postgres;

create sequence domain_seq
    increment by 50;

alter sequence domain_seq owner to postgres;

create sequence keywords_seq
    increment by 50;

alter sequence keywords_seq owner to postgres;

create sequence openanswer_seq
    increment by 50;

alter sequence openanswer_seq owner to postgres;

create sequence question_seq
    increment by 50;

alter sequence question_seq owner to postgres;

create sequence questiontypes_seq
    increment by 50;

alter sequence questiontypes_seq owner to postgres;

create sequence test_seq
    increment by 50;

alter sequence test_seq owner to postgres;

create table domain
(
    id   integer      not null
        primary key,
    name varchar(255) not null
        unique
);

alter table domain
    owner to postgres;

create table enterprise
(
    domain_id integer
        constraint fkf613qq9yblag6tnf0jo8u94fj
            references domain,
    id        uuid         not null
        primary key,
    name      varchar(255) not null
        unique
);

alter table enterprise
    owner to postgres;

create table adminaccount
(
    id            bigint       not null
        primary key,
    enterprise_id uuid
        constraint fkk7nj8yiote0algjs3nw9lb3ra
            references enterprise,
    password      varchar(255) not null,
    username      varchar(255) not null
        unique
);

alter table adminaccount
    owner to postgres;

create table questiontypes
(
    id   integer      not null
        primary key,
    type varchar(255) not null
        unique
);

alter table questiontypes
    owner to postgres;

create table question
(
    id                integer          not null
        primary key,
    points            double precision not null,
    question_types_id integer
        constraint fk60ila166at6bxk75fl7ajb590
            references questiontypes,
    hint              varchar(255),
    label             varchar(255)     not null,
    enterprise_id     uuid
        constraint question_enterprise_id_fk
            references enterprise
);

alter table question
    owner to postgres;

create table test
(
    durationminute   integer      not null,
    id               integer      not null
        primary key,
    isactive         boolean      not null,
    ispublic         boolean,
    admin_account_id bigint
        constraint fkabf2yxe0n19t3xvqhpjpaqhs9
            references adminaccount,
    enterprise_id    uuid
        constraint fkm0b3nxy8okyn66rd2k9yo9fs7
            references enterprise,
    name             varchar(255) not null
);

alter table test
    owner to postgres;

create table test_questions
(
    id          integer generated by default as identity
        primary key,
    position    integer not null,
    question_id integer
        constraint fk8caqwloqteduwe2x2iyqu47xq
            references question,
    test_id     integer
        constraint fkkjyuua3xik5uveu6lfv2keh7e
            references test
);

alter table test_questions
    owner to postgres;

create table test_session
(
    score          integer,
    tokenused      boolean      not null,
    endtime        timestamp(6),
    id             bigint generated by default as identity
        primary key,
    starttime      timestamp(6),
    tokenexpiresat timestamp(6),
    candidateemail varchar(255) not null,
    status         varchar(255)
        constraint test_session_status_check
            check ((status)::text = ANY
        ((ARRAY ['PLANNED'::character varying, 'SCHEDULED'::character varying, 'ACTIVE'::character varying, 'FINISHED'::character varying])::text[])),
    token          varchar(255) not null
        unique
);

alter table test_session
    owner to postgres;

create table answer
(
    id          integer      not null
        primary key,
    is_correct  boolean      not null,
    question_id integer
        constraint fkfiomvt17psxodcis3d8nmopx8
            references question,
    label       varchar(255) not null
);

alter table answer
    owner to postgres;

create table openanswer
(
    id             integer      not null
        primary key,
    question_id    integer
        unique
        constraint fkiecfy0d2la41dxpqkr5cc5o78
            references question,
    expectedanswer varchar(255) not null
);

alter table openanswer
    owner to postgres;

create table keywords
(
    id             integer      not null
        primary key,
    open_answer_id integer
        constraint fka405w21rbyr68xm31579g36yp
            references openanswer,
    keyword        varchar(255) not null
);

alter table keywords
    owner to postgres;

create table openanswer_keywords
(
    openanswer_id integer not null
        constraint fkkiqgj59pvvrr6ygcyyy9lpi43
            references openanswer,
    keywords_id   integer not null
        unique
        constraint fkmk8flthk6ga858s9c39ly59rq
            references keywords,
    primary key (openanswer_id, keywords_id)
);

alter table openanswer_keywords
    owner to postgres;

